spring:
  application:
    name: triones-backend
  datasource:
    name: dataSource
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      driver-class-name: org.postgresql.Driver
  jackson:
    locale: zh_CN
    time-zone: Asia/Shanghai
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  messages:
    basename: i18n/validation

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-prefix: dao.
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

springdoc:
  show-actuator: false
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

triones:
  exception:
    resource-paths: i18n/error

#logging:
#  level:
#    org.springframework.web: INFO
#    com.github.binarywang.demo.wx.mp: DEBUG
#    me.chanjar.weixin: DEBUG
